# https://devguide.python.org/#branchstatus
# https://www.djangoproject.com/download/#supported-versions
# https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django

language: python
os: linux
dist: xenial
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
env:
  global:
    - SUITE="tests/functional"
jobs:
  allow_failures:
    - python: 3.4  # todo: figure out reqs for coverage

  include:

    # django tests
    - stage: django tests

    # django 1.11
      python: 2.7
      env:
        - DJANGO=1.11
        - SUITE="tests/dj"
    - python: 3.4
      env:
        - DJANGO=1.11
        - SUITE="tests/dj"
    - python: 3.5
      env:
        - DJANGO=1.11
        - SUITE="tests/dj"
    - python: 3.6
      env:
        - DJANGO=1.11
        - SUITE="tests/dj"
    - python: 3.7
      env:
        - DJANGO=1.11
        - SUITE="tests/dj"

    # django 2.0

    - python: 3.4
      env:
        - DJANGO=2.0
        - SUITE="tests/dj"
    - python: 3.5
      env:
        - DJANGO=2.0
        - SUITE="tests/dj"
    - python: 3.6
      env:
        - DJANGO=2.0
        - SUITE="tests/dj"
    - python: 3.7
      env:
        - DJANGO=2.0
        - SUITE="tests/dj"

    # django 2.1

    - python: 3.5
      env:
        - DJANGO=2.1
        - SUITE="tests/dj"
    - python: 3.6
      env:
        - DJANGO=2.1
        - SUITE="tests/dj"
    - python: 3.7
      env:
        - DJANGO=2.1
        - SUITE="tests/dj"

    # django 2.2

    - python: 3.5
      env:
        - DJANGO=2.2
        - SUITE="tests/dj"
    - python: 3.6
      env:
        - DJANGO=2.2
        - SUITE="tests/dj"
    - python: 3.7
      env:
        - DJANGO=2.2
        - SUITE="tests/dj"
    - python: 3.8
      env:
        - DJANGO=2.2
        - SUITE="tests/dj"

    # django 3.0

    - python: 3.6
      env:
        - DJANGO=3.0
        - SUITE="tests/dj"
    - python: 3.7
      env:
        - DJANGO=3.0
        - SUITE="tests/dj"
    - python: 3.8
      env:
        - DJANGO=3.0
        - SUITE="tests/dj"

    # integration tests
    - stage: integration tests
      python: 2.7
      env: SUITE="tests/integration"
    - stage: integration tests
      python: 3.7
      env: SUITE="tests/integration"

cache:
  directories:
    - $HOME/.cache/pip
install:
  - if [[ $DJANGO != '' ]]; then pip install django~=$DJANGO.0; fi
  - pip install 'requests>=1.0' 'python-dateutil>=2.1' 'six>=1.2.0'
  - pip install pytest-cov
  - if [[ $TRAVIS_PYTHON_VERSION != '3.4.*' ]]; then pip install python-coveralls; else pip install 'python-coveralls==2.9.1'; fi
  - pip install -e .
script: py.test $SUITE --cov=pyuploadcare
notifications:
  email:
    recipients:
      - ak@uploadcare.com
      - dm@uploadcare.com
    on_success: change
    on_failure: change

after_success:
  coveralls
